
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.example.practica1.analizador;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LINEA = 5;
  public static final int MULTIPLICACION = 16;
  public static final int DIVISION = 17;
  public static final int SUMA = 14;
  public static final int CURVA = 4;
  public static final int ANIMAR = 11;
  public static final int COLOR = 3;
  public static final int CUADRADO = 7;
  public static final int OBJETO = 12;
  public static final int GRAFICAR = 10;
  public static final int COMA = 20;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int POLIGONO = 9;
  public static final int CIRCULO = 6;
  public static final int ENTERO = 2;
  public static final int ANTERIOR = 13;
  public static final int PARENTESISB = 19;
  public static final int PARENTESISA = 18;
  public static final int RECTANGULO = 8;
  public static final int RESTA = 15;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ENTERO",
  "COLOR",
  "CURVA",
  "LINEA",
  "CIRCULO",
  "CUADRADO",
  "RECTANGULO",
  "POLIGONO",
  "GRAFICAR",
  "ANIMAR",
  "OBJETO",
  "ANTERIOR",
  "SUMA",
  "RESTA",
  "MULTIPLICACION",
  "DIVISION",
  "PARENTESISA",
  "PARENTESISB",
  "COMA"
  };
}

