
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LINEA = 6;
  public static final int MULTIPLICACION = 17;
  public static final int DIVISION = 18;
  public static final int SUMA = 15;
  public static final int CURVA = 5;
  public static final int ANIMAR = 12;
  public static final int ERROR = 22;
  public static final int COLOR = 4;
  public static final int CUADRADO = 8;
  public static final int OBJETO = 13;
  public static final int ENTER = 2;
  public static final int GRAFICAR = 11;
  public static final int COMA = 21;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int POLIGONO = 10;
  public static final int CIRCULO = 7;
  public static final int ENTERO = 3;
  public static final int ANTERIOR = 14;
  public static final int PARENTESISB = 20;
  public static final int PARENTESISA = 19;
  public static final int RECTANGULO = 9;
  public static final int RESTA = 16;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ENTER",
  "ENTERO",
  "COLOR",
  "CURVA",
  "LINEA",
  "CIRCULO",
  "CUADRADO",
  "RECTANGULO",
  "POLIGONO",
  "GRAFICAR",
  "ANIMAR",
  "OBJETO",
  "ANTERIOR",
  "SUMA",
  "RESTA",
  "MULTIPLICACION",
  "DIVISION",
  "PARENTESISA",
  "PARENTESISB",
  "COMA",
  "ERROR"
  };
}

